### ISSUE TITLE
Governance of release process

### ISSUE THREAD

**Issue by galuszkak** [Segfault-Inc/Multicorn#221]
Hey,

We are moving discussion with @rdunklau @liZe that we started in #210 about release process.

What I understand Kozea is open source organization like JazzBand (You are welcome to join and contribute to our open source projects).

The problem that I raised is what is release process now to pgxn as my understanding this is a way to distribute Multicorn project.

I don't think we have Multicorn project/organization via question from @rdunklau , it's just Kozea. Now package is distributed via pgxn on one person account. There is a pending question if there is organisation/team concept in pgxn release accounts.

**Comment by rdunklau** [comment]
During a transition period, if you want to make a release just ping me here or assign an issue to me regarding a release and I'll upload it.

**Comment by KAction** [comment]
I'd like to have my pull request #231 to be merged and get it into official release. I guess, to speed up this process I need to setup CI myself. Something else?

**Comment by KAction** [comment]
@rdunklau Ping? Any chance for proper release, that includes #231?

**Comment by KAction** [comment]
@galuszkak @rdunklau Hello? Still waiting for release.

If everything else fails, I'll have to fork and release as `multicorn2` on `pgnx.org`.

**Comment by galuszkak** [comment]
@KAction I'm preparing TravisCI CI/CD pipeline. I should have it next week ready. Unfortunetly docheck script has a lot of bugs that I'm fixing now. I will probably move this to docker-compose. and add support for PostgreSQL 9.4 and 9.5 that was accidently broken that should be fixed before release.

Unfortunetly I don't have release rights this can only be done by @rdunklau

**Comment by rdunklau** [comment]
@galuszkak I think I thought of a solution to this problem: 
  - create a multicorn account on pgxn
  - ask the pgxn maintainer to transfer the multicorn project to this account
  - store the multicorn account password in the repo, ciphered using GPG (your key and any other one).

What do you think ?

**Comment by KAction** [comment]
If you need another key keeper, I volunteer: [key](https://db.debian.org/fetchkey.cgi?fingerprint=7214B3C8D5FF8F26E12593D52E20FEEE71FC7D81)

**Comment by df7cb** [comment]
Ping? The project is rotting away, and no visible progress is being made. Maintaining the Debian package is becoming more and more difficult. Now it's exploding with python3 upgraded to 3.8: #245 

Does it make sense to wait for this to be fixed, or should I stop worrying and remove the package from Debian and apt.postgresql.org?

**Comment by rdunklau** [comment]
Hi Christophe,

Since my attempts at transferring the responsibilities for maintaining and releasing this project have failed, I'm taking my responsibilities and will take back maintenance for it, it would be a shame to see it dying.

One of my main concerns was that the Kozea group had no interest in contributing to it anymore.

As you can see, I transferred it's ownership to the Segfault-Inc organization which we setup with @rjuju a while ago.

Let me get back to you regarding your pull requests in the next few days / weeks.

Thanks for your patience,

Best regards.

**Comment by df7cb** [comment]
Thanks! Looking forward to it.

Fwiw, if you want to cross-check with the patch stack in Debian, it's there: https://salsa.debian.org/postgresql/postgresql-multicorn/-/tree/master/debian/patches

**Comment by galuszkak** [comment]
@rdunklau I've lost my merging privileges even if I contributed a little in past months. Could you restore that? I'm still interested in some contribution in the coming months.

**Comment by rdunklau** [comment]
@galuszkak Thank you for the great job you did for the past year !  Right after I moved the repo, I added you with "Write" permissions which should alllow you to merge, but it shows you in a status "Pending invite" so I guess you should have received an email inviting you to do so. Sorry about the disruption.
