### ISSUE TITLE
Build failure with PG12: src/multicorn.h:16:10: fatal error: nodes/relation.h: No such file or directory

### ISSUE THREAD

**Issue by df7cb** [Segfault-Inc/Multicorn#223]
Building against PG 12beta1:
```
17:57:48 creating build/temp.linux-amd64-2.7/src
17:57:48 x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/postgresql -I/usr/include/postgresql -I/usr/include/postgresql/12/server -I/usr/include/python2.7 -c src/utils.c -o build/temp.linux-amd64-2.7/src/utils.o -shared
17:57:48 In file included from /usr/include/postgresql/12/server/foreign/fdwapi.h:17,
17:57:48                  from src/multicorn.h:9,
17:57:48                  from src/utils.c:17:
17:57:48 /usr/include/postgresql/12/server/nodes/pathnodes.h:834:2: warning: function declaration isn't a prototype [-Wstrict-prototypes]
17:57:48   void  (*amcostestimate) (); /* AM's cost estimator */
17:57:48   ^~~~
17:57:48 In file included from src/utils.c:17:
17:57:48 src/multicorn.h:16:10: fatal error: nodes/relation.h: No such file or directory
17:57:48  #include "nodes/relation.h"
17:57:48           ^~~~~~~~~~~~~~~~~~
17:57:48 compilation terminated.
```

Is Multicorn still supported? Even building against 9.6 is still broken (#171). Packagers would very much appreciate if we didn't have to carry a ton of patches.

**Comment by galuszkak** [comment]
@df7cb I'm doing some cleanup (removing older version support of PostgreSQL (we will support only 9.6 and above) and dropping support for python2.6. 

I hope to enable also Continous integration on Travis with that.

**Comment by ergo70** [comment]
nodes/relation.h is now nodes/pathnodes.h
optimizer/var.h is now optimizer/optimizer.h

but then:

too few arguments to function ‘get_attname’

**Comment by ergo70** [comment]
Ah, this is a problem since 11. Add the neccessary boolean to get_attname in query.c and it compiles.

**Comment by ranjanprj** [comment]
Can  a pull request be created

**Comment by ranjanprj** [comment]
pull request submitted

**Comment by devrimgunduz** [comment]
What's the status on this?

**Comment by rais2-pivotal** [comment]
Did anyone get past this ?

**Comment by devrimgunduz** [comment]
ping.

**Comment by ranjanprj** [comment]
https://github.com/Kozea/Multicorn/pull/232

**Comment by df7cb** [comment]
I got the Debian package working by packaging a git snapshot, but it would be cool to finally have a new release.

**Comment by rdunklau** [comment]
Hi Christoph,

I'm no longer maintaining this repo and @liZe gave away the responsibility of maintenance to @galuszkak. As described in issue https://github.com/Kozea/Multicorn/issues/221, I have created a new PGXN account to move the ownership to somebody else.

I'm waiting for @galuszkak GPG key to give them the password for this new account.

I know you are a trustworthy packager, so if you are interested in this, please let me know.

**Comment by df7cb** [comment]
TBH, PGXN makes things more complicated than they could be. Pushing tags to github and clicking on "make new release" is way easier. If that's what's preventing new multicorn releases, the PGXN part should be reconsidered. (The Debian package is pulling tarballs from github anyway.)

Thanks for the offer, but I don't think I'll have time to do upstream work on multicorn as I have too many things on my plate already.

**Comment by galuszkak** [comment]
@rdunklau I'm in the process of rescuing my GPG key ( this key:  rsa2048/d340b51b614397f62fb664f44ded77e0cf4b9c51 ( you can find it here: https://keyserver.ubuntu.com/ )  to generate a new one. My old key expired and I want to sign my new key with old one to broadcast it to make sure my identity has continuity. Unfortunately, I have a problem with my backup. Whenever that will happen which I hope will happen this week I will send you my new key.

I'm also working on TravisCI to deploy it this week.

**Comment by devrimgunduz** [comment]
Hi,

When cat we get a new release?

Thanks. Devrim

**Comment by rdunklau** [comment]
This has been merged, a new release will come out really soon now.
